# Generated by Django 5.0.14 on 2026-07-15 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offerings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('author_name', models.CharField(max_length=120, verbose_name='Author name')),
                ('author_role', models.CharField(blank=True, max_length=150, verbose_name='Author role')),
                ('author_role_fa', models.CharField(blank=True, max_length=150, null=True, verbose_name='Author role')),
                ('author_role_ckb', models.CharField(blank=True, max_length=150, null=True, verbose_name='Author role')),
                ('quote', models.TextField(verbose_name='Quote')),
                ('quote_fa', models.TextField(null=True, verbose_name='Quote')),
                ('quote_ckb', models.TextField(null=True, verbose_name='Quote')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/%Y/%m/', verbose_name='Photo')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='offerings.offering', verbose_name='Offering')),
            ],
            options={
                'verbose_name': 'testimonial',
                'verbose_name_plural': 'testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
