# Generated by Django 5.0.14 on 2026-07-15 13:59

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/%Y/%m/', validators=[apps.core.validators.validate_image_file], verbose_name='Photo'),
        ),
    ]
