# Generated by Django 5.0.14 on 2026-07-15 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_seed_navitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navitem',
            options={'ordering': ['order'], 'verbose_name': 'navigation item', 'verbose_name_plural': 'navigation items'},
        ),
        migrations.AlterField(
            model_name='navitem',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='The phased-rollout switch. Blog starts True, everything else False.', verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.navitem', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='title_ckb',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='title_fa',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='url_name',
            field=models.CharField(help_text="Named URL to resolve, e.g. 'blog:list'", max_length=100, verbose_name='URL name'),
        ),
    ]
