# Generated by Django 5.0.14 on 2026-07-15 13:59

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_author_options_alter_author_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='authors/', validators=[apps.core.validators.validate_image_file], verbose_name='Avatar'),
        ),
    ]
