# Generated by Django 5.0.14 on 2026-07-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Prod Blog', max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('social_links', models.JSONField(blank=True, default=dict, help_text="e.g. {'instagram': 'https://...', 'telegram': 'https://...'}")),
                ('meta_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThemeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.JSONField(blank=True, default=dict, help_text="Brand color tokens, e.g. {'brand': '#0f9d8e', 'accent': '#f0b429'}")),
                ('default_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
