# Generated by Django 5.0.14 on 2026-07-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'site settings', 'verbose_name_plural': 'site settings'},
        ),
        migrations.AlterModelOptions(
            name='themeconfig',
            options={'verbose_name': 'theme configuration', 'verbose_name_plural': 'theme configuration'},
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='Prod Blog', max_length=120, verbose_name='Site name'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text="e.g. {'instagram': 'https://...', 'telegram': 'https://...'}", verbose_name='Social links'),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='colors',
            field=models.JSONField(blank=True, default=dict, help_text="Brand color tokens, e.g. {'brand': '#0f9d8e', 'accent': '#f0b429'}", verbose_name='Colors'),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='default_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=5, verbose_name='Default mode'),
        ),
    ]
