# Generated by Django 5.0.14 on 2026-07-15 13:59

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesetting_options_alter_themeconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', validators=[apps.core.validators.validate_image_file], verbose_name='Logo'),
        ),
    ]
