# Generated by Django 5.0.14 on 2026-07-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitesetting_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='وبلاگ', max_length=120, verbose_name='Site name'),
        ),
    ]
