# Generated by Django 5.0.14 on 2026-07-15 11:39

import apps.leads.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadMagnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta title')),
                ('meta_title_fa', models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta title')),
                ('meta_title_ckb', models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('meta_description_fa', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta description')),
                ('meta_description_ckb', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta description')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_fa', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_ckb', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ckb', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='leads/%Y/%m/', verbose_name='Cover image')),
                ('file', models.FileField(upload_to='leads/files/%Y/%m/', validators=[apps.leads.models.validate_upload_size], verbose_name='File')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'lead magnet',
                'verbose_name_plural': 'lead magnets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_contacted', models.BooleanField(default=False, verbose_name='Contacted')),
                ('lead_magnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='leads.leadmagnet', verbose_name='Lead magnet')),
            ],
            options={
                'verbose_name': 'submission',
                'verbose_name_plural': 'submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
