# Generated by Django 5.0.14 on 2026-07-18 15:10

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.contrib.postgres.search import SearchVector
from django.db import migrations


def backfill_search_vectors(apps, schema_editor):
    Post = apps.get_model("blog", "Post")
    Post.objects.update(
        search_vector_fa=SearchVector("title_fa", "excerpt_fa", "body_fa"),
        search_vector_ckb=SearchVector("title_ckb", "excerpt_ckb", "body_ckb"),
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_cover_image'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='search_vector_ckb',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='search_vector_fa',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_fa'], name='blog_post_search_fa_gin'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_ckb'], name='blog_post_search_ckb_gin'),
        ),
        migrations.RunPython(backfill_search_vectors, noop),
    ]
