# Generated by Django 5.0.14 on 2026-07-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_search_vector_ckb_post_search_vector_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Views'),
        ),
    ]
