# Generated by Django 5.0.14 on 2026-07-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta title')),
                ('meta_title_fa', models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta title')),
                ('meta_title_ckb', models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('meta_description_fa', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta description')),
                ('meta_description_ckb', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta description')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_fa', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_ckb', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('slug', models.SlugField(help_text="Must match a routed page name, e.g. 'about' or 'contact'.", max_length=100, unique=True, verbose_name='Slug')),
                ('body', models.TextField(blank=True, verbose_name='Body')),
                ('body_fa', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('body_ckb', models.TextField(blank=True, null=True, verbose_name='Body')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ['title'],
            },
        ),
    ]
