# Generated by Django 5.0.14 on 2026-07-15 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta title')),
                ('meta_title_fa', models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta title')),
                ('meta_title_ckb', models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('meta_description_fa', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta description')),
                ('meta_description_ckb', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta description')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_fa', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_ckb', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='Summary')),
                ('summary_fa', models.CharField(blank=True, max_length=300, null=True, verbose_name='Summary')),
                ('summary_ckb', models.CharField(blank=True, max_length=300, null=True, verbose_name='Summary')),
                ('body', models.TextField(blank=True, verbose_name='Body')),
                ('body_fa', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('body_ckb', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='offerings/%Y/%m/', verbose_name='Cover image')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'offering',
                'verbose_name_plural': 'offerings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('starts_at', models.DateTimeField(verbose_name='Starts at')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Ends at')),
                ('location', models.CharField(blank=True, help_text='Online link or venue address', max_length=200, verbose_name='Location')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacity')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='offerings.offering', verbose_name='Offering')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Phone')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='offerings.offering', verbose_name='Offering')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='offerings.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'enrollment',
                'verbose_name_plural': 'enrollments',
                'ordering': ['-created_at'],
            },
        ),
    ]
